#!/usr/bin/env bash

case "$1" in
    "rb" | "rbp" | "rebuild")
        scripts/rebuildPatches.sh || exit 1
    ;;
    "p" | "patch")
        scripts/build.sh || exit 1
    ;;
    "m" | "up" | "merge")
        scripts/mergeUpstream.sh || exit 1
    ;;
    "b" | "build")
        scripts/build.sh --jar || exit 1
    ;;
    "e" | "edit")
        scripts/edit.sh || exit 1
    ;;
    *)
        echo "RedMinecraft build tool command. This provides a variety of commands to control the RedMinecraft"
        echo "build. View below for details of the available commands."
        echo ""
        echo "Commands:"
        echo "  * rb, rbp, rebuild | Rebuilds the patches"
        echo "  * p, patch         | Applies all the patches to Waterfall"
        echo "  * m, up, merge     | Utility to aid in merging upstream"
        echo "  * b, build         | Builds the project"
        echo "                     | The bootstrap artifact can be found in RedMinecraft-Proxy/bootstrap/target/"
        echo "  * e, edit          | Runs git rebase -i for RedMinecraft, allowing patches to be easily modified"
    ;;
esac
